name: dependency_visitor
description: Visits root package, transitive and immediate dependencies in order to search given files.
version: 1.0.1
homepage: https://github.com/owczaro/dependency_visitor

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  effective_dart: ^1.3.2
  path: ^1.8.0
  equatable: ^2.0.3
  universal_io: ^2.0.4
  yaml: ^3.1.0
  pubspec_lock_reader: ^1.0.1

dev_dependencies:
  test: ^1.17.12
