name: dependency_visitor
description: Visits root package, transitive and immediate dependencies in order to search given files.
version: 0.1.4
homepage: https://github.com/owczaro/dependency_visitor

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  effective_dart: ^1.2.4
  path: ^1.7.0
  yaml: ^2.2.1
  equatable: ^1.2.4
  pubspec_lock: ^2.0.1
  meta: ^1.2.2
  universal_io: ^1.0.1

dev_dependencies:
  test: ^1.14.4
